#!/usr/local/bin/python3.7

import requests
import argparse
import time

parser=argparse.ArgumentParser()
parser.add_argument('ip_address', help="Enter the ip address and hostname")
parser.add_argument('--p', help="Enter the port number")
args=parser.parse_args()

try:
    reply=requests.head(f"http://{args.ip_address}:{args.p}/cars")
    if reply.status_code == requests.codes.OK:
        print("Webserver is responding...")
    time.sleep(5)
    print('Test success')
except requests.RequestException:
    print('Connection error..Test Failed')

